[FIO internal] apalix-imx8: up-port initial implementation
Boot test:
U-Boot 2020.04-00118-gea539ce4dc-dirty (Jul 31 2020 - 22:57:53 +0300)

CPU:   NXP i.MX8QM RevB A53 at 1200 MHz

DRAM:  4 GiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1, FSL_SDHC: 2
Loading Environment from MMC... OK
In:    serial@5a070000
Out:   serial@5a070000
Err:   serial@5a070000
Model: Toradex Apalis iMX8 QuadMax 4GB Wi-Fi / BT IT V1.0B, Serial# 06438736
switch to partitions #0, OK
-----------------------------------------
Was tested with:
imx-mkimage: imx_5.4.24_2.1.0
imx-scfw: ab182211e("Update .gitignore to ignore our built files...")
imx-atf: imx_5.4.24_2.1.0
imx-seco: 3.6.3 [1]
-----------------------------------------

Set fdt_high to 0xffffffffffffffff in order to avoid copying fdt
during boot. It fixes allocation error [2].

Note that such solution can't be upstreamed (see [3]).

[1] https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx-seco-3.6.3.bin
[2]
...
   Loading fdt from 0x86dd0a38 to 0x83000000
   Booting using the fdt blob at 0x83000000
   Uncompressing Kernel Image
   Loading Ramdisk to fb32c000, end fb67a669 ... OK
ERROR: Failed to allocate 0x22ff9 bytes below 0xfe000000.
device tree - allocation error
FDT creation failed! hanging...### ERROR ### Please RESET the board ###
...
[3]
  https://patchwork.ozlabs.org/project/uboot/patch/20210722154943.127775-2-oleksandr.suvorov@toradex.com/#2723077

Signed-off-by: Igor Opaniuk <igor.opaniuk@toradex.com>
Co-developed-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>